[package]
name = "clap_repro"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
# clap = { version = "3.0.0-beta.5", features = ["debug"] }

# Automatically parses the version.
structopt = "0.3.23"
